/*
* Even Fibonacci numbers
* Problem 2
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* SOLUTION: 4613732
 */

package projecteuler;

/**
 *
 * @author sbenjamin
 */
public class problem2 {
  long sum = 0;
  long prev1=1, prev2=2;
    
  public long fib(long n) {       
       
    while (prev2<n) {        
         if (prev2%2==0) {                             
             sum = sum + prev2;
         }          
         long savePrev1 = prev1; //0
         prev1 = prev2;
         prev2 = savePrev1 + prev2;                       
     }
   return sum;
   }
}